#Container name automatically the name of whatever the parent folder is
name: Footlocker
services:
  kickbot:
    build:
      context: /home/tyler/Documents/ShoeBot_Pi
      dockerfile: Dockerfile
    image: kickbot
    container_name: Footlocker
    stdin_open: true   # -i
    tty: true           # -t
    volumes:
      - /home/tyler/Documents/ShoeBot_Pi/sros_ws:/root/colcon_ws
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0


    #Temporary for dev: sleep infinity
    # entrypoint: ["sh", "-c", "sleep infinity"]

    #Temporarily suppress for dev -> Consider adding --break-system-packages to pip install commmand if we get errors about pip
    command: >
      bash -c "source /ros_entrypoint.sh &&
               cd /root/colcon_ws && colcon build --executor sequential &&
               cd ./launch && bash kickstart_motor_test.sh"